name: Prepare CI
description: This action prepare CI that restore cachable items

runs:
    using: composite
    steps:
        - name: Get npm cache directory
          id: npm-cache-dir
          shell: bash
          run: echo "::set-output name=dir::$(npm config get cache)"
        - name: Restore dependencies from cache
          uses: actions/cache@v3
          id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
          with:
              path: ${{ steps.npm-cache-dir.outputs.dir }}
              key: v0-${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
              restore-keys: |
                  v0-${{ runner.os }}-npm-
        - name: Install dependencies
          shell: bash
          # We only cache `npm config get cache`, not including `node_modules/`.
          # thus we need to do `npm ci` to restore `node_modules/` so we need run always this step.
          # if: steps.npm-cache.outputs.cache-hit != 'true'
          run: npm ci
