name: Prepare CI
description: This action prepare CI that restore cachable items

inputs:
    node-version:
        required: true

runs:
    using: composite
    steps:
        # Ideally, we run every CI jobs in some containers as a hermetic to make it easy to reproduce the environment locally.
        # However,
        #   1. Recently, it is delayed to update of Node.js' docker image.
        #      This would not be a high impact problem but this is a remarkable problem for major version.
        #      It sometimes 3~4 weeks delay. We cannot test with a new version immidiately.
        #   2. Old actions/setup-node (v1) cannot install the Node.js that is not listed in the action's database.
        #      It's slower than a docker image. See https://github.com/option-t/option-t/pull/681#issuecomment-658219488
        #      But the recent version of its GH action does not such problem.
        #   3. GH Action job is enough to hermetic to achieve, I think. Any fork can them in their forked repository,
        #      and each of steps of them are almost portable to reproduce them for this project's purpose.
        # So we use `actions/setup-node` simply.
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
              node-version: ${{ inputs.node-version }}
        - name: Get npm cache directory
          shell: bash
          id: npm-cache-dir
          run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
        - name: Restore dependencies from cache
          id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
          uses: actions/cache@v3
          with:
              path: ${{ steps.npm-cache-dir.outputs.dir }}
              key: v0-${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
              restore-keys: |
                  v0-${{ runner.os }}-npm-
        - name: Install dependencies
          shell: bash
          # We only cache `npm config get cache`, not including `node_modules/`.
          # thus we need to do `npm ci` to restore `node_modules/` so we need run always this step.
          # if: steps.npm-cache.outputs.cache-hit != 'true'
          run: npm ci
