name: Download a build artifact
description: This action provides a uniform way to download a build artifact.

inputs:
    git-sha:
        required: true
    working-directory:
        default: ${{ github.workspace }}
        required: false

runs:
    using: composite
    steps:
        - uses: actions/download-artifact@v3
          with:
              name: artifacts-${{ inputs.git-sha }}
              path: ${{ inputs.working-directory }}/__dist
