name: CI workflow template
# we need separate CI workflow template to achieve that a CI
# for each of PRs cancellable and one for default branch should run on every commits
# because the runner will use `concurrency.group` in the callee worfklow which is
# configured as cancellable if we don't set `concurrency.group` to caller workflow.
on:
    workflow_call:

permissions:
    contents: read

jobs:
    install_dependencies:
        runs-on: ubuntu-latest
        container: node:${{ matrix.node-version }}-bullseye

        strategy:
            matrix:
                node-version:
                    # We think that we don't have to specify all versions which we'd like to test
                    # because almost npm packages cares about platform but don't care about node's version.
                    - 18

        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/prepare_ci

    format_check:
        needs: [install_dependencies]
        runs-on: ubuntu-latest
        container: node:${{ matrix.node-version }}-bullseye

        strategy:
            matrix:
                node-version:
                    - 18

        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/prepare_ci

            - run: make format_check -j
              env:
                  CI: true

    lint:
        needs: [install_dependencies]
        runs-on: ubuntu-latest
        container: node:${{ matrix.node-version }}-bullseye

        strategy:
            matrix:
                node-version:
                    - 18

        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/prepare_ci

            - run: make lint -j
              env:
                  CI: true

    build:
        needs: [install_dependencies]
        runs-on: ubuntu-latest
        container: node:${{ matrix.node-version }}-bullseye

        strategy:
            matrix:
                node-version:
                    - 18

        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/prepare_ci

            - run: make build -j
              env:
                  CI: true

    unittest:
        needs: [install_dependencies]
        runs-on: ubuntu-latest
        container: node:${{ matrix.node-version }}-bullseye

        strategy:
            matrix:
                node-version:
                    - 18

        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/prepare_ci

            - run: make test_unittest -j
              env:
                  CI: true

    test_package_json_exports_field_format:
        needs: [install_dependencies]
        runs-on: ubuntu-latest
        container: node:${{ matrix.node-version }}-bullseye

        strategy:
            matrix:
                node-version:
                    - 18
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/prepare_ci
            - run: make test_package_json_exports_field_format -j
              env:
                  CI: true

    test_import_types:
        needs: [install_dependencies]
        runs-on: ubuntu-latest
        container: node:${{ matrix.node-version }}-bullseye

        strategy:
            matrix:
                node-version:
                    - 18
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/prepare_ci
            - run: make test_import_types -j
              env:
                  CI: true
