name: publish to npm
on:
    release:
        types: [released]
permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/prepare_ci
              with:
                  node-version: 18
            - run: npm ci
            - run: make clean
            - run: make prepublish -j
            - run: make publish -j
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
